# -----------------------------
# Aartheis Atlas
# StoneBound Fate Campaign Site
# -----------------------------

# --- Required options --- #

title: Aartheis Atlas

description: "A campaign atlas for StoneBound Fate: sessions, NPCs, factions, locations, maps, and house rules."

author: Aaron Graifman

# Required for GitHub Project Pages
url: "https://aaron13g.github.io"
baseurl: "/hero-dnd-site"

# --- Navigation Bar --- #

navbar-links:
  Home: ""
  StoneBound Fate:
    - Atlas Home: "atlas/"
    - Sessions: "atlas/sessions"
    - NPCs: "atlas/npcs"
    - Locations: "atlas/locations"
    - Factions: "atlas/factions"
    - Rules: "atlas/rules"
 # Table Demo: "table-demo"

# --- Logo --- #

avatar: "assets/img/hubert-logo.jpg"
round-avatar: true

# --- Footer Social Links --- #

social-network-links:
  email: "aaronmgraifman@gmail.com"
  github: aaron13g
  linkedin: aaron-graifman

rss-description: StoneBound Fate campaign updates and reference materials.

# --- General Options --- #

share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  vk: false

url-pretty: "aaron13g.github.io/hero-dnd-site"

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true

# --- Colour Scheme --- #

navbar-col: "#5A0B12"
navbar-text-col: "#F4EFE6"
navbar-children-col: "#7A0F19"
navbar-border-col: "#A8841E"

page-col: "#F4EFE6"
text-col: "#1F1A17"

link-col: "#7A0F19"
hover-col: "#C6A84B"

footer-col: "#14110F"
footer-text-col: "#E8DDC8"
footer-link-col: "#C6A84B"


# --- Date / Markdown --- #

timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# --- Defaults --- #

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
  -
    scope:
      path: ""
    values:
      layout: "page"

# --- Exclusions --- #

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
collections:
  npcs:
    output: true
    permalink: /atlas/npcs/:name/
  factions:
    output: true
    permalink: /atlas/factions/:name/
  locations:
    output: true
    permalink: /atlas/locations/:name/
  sessions:
    output: true
    permalink: /atlas/sessions/:name/
  items:
    output: true
    permalink: /atlas/items/:name/
  events:
    output: true
    permalink: /atlas/events/:name/

site-css:
  - "/assets/css/custom-fonts.css"
  - "/assets/css/typography.css"
  - "/assets/css/custom-button.css"
  # - "/assets/css/enter-transition.css"
  - "/assets/css/logo-adjust.css"
  - "/assets/css/home-hub.css"
  - "/assets/css/npc-table.css"
  - "/assets/css/npc-profile.css"




site-js:
  #  - "/assets/js/enter-transition.js"


